[package]
name = "cudart"
version = "0.1.0-devel"
authors = ["Peter Jin <peterhaijin@gmail.com>"]
license = "BSD-2-Clause"
description = "CUDA API bindings."
repository = "https://github.com/peterhj/cudart"
keywords = ["cuda"]
build = "build.rs"

[features]
default         = []
cuda_6_5        = []
cuda_7_0        = ["gte_cuda_7_0"]
cuda_7_5        = ["gte_cuda_7_0", "gte_cuda_7_5"]
cuda_8_0        = ["gte_cuda_7_0", "gte_cuda_7_5", "gte_cuda_8_0"]
cuda_9_0        = ["gte_cuda_7_0", "gte_cuda_7_5", "gte_cuda_8_0", "gte_cuda_9_0"]
cuda_9_1        = ["gte_cuda_7_0", "gte_cuda_7_5", "gte_cuda_8_0", "gte_cuda_9_0", "gte_cuda_9_1"]
cuda_9_2        = ["gte_cuda_7_0", "gte_cuda_7_5", "gte_cuda_8_0", "gte_cuda_9_0", "gte_cuda_9_1", "gte_cuda_9_2"]
cuda_10_0       = ["gte_cuda_7_0", "gte_cuda_7_5", "gte_cuda_8_0", "gte_cuda_9_0", "gte_cuda_9_1", "gte_cuda_9_2", "gte_cuda_10_0"]
gte_cuda_7_0    = []
gte_cuda_7_5    = []
gte_cuda_8_0    = []
gte_cuda_9_0    = []
gte_cuda_9_1    = []
gte_cuda_9_2    = []
gte_cuda_10_0   = []

[build-dependencies]
bindgen = "^0.38"

[dependencies]
static_assertions = "0.3.1"

[lib]
name = "cudart"
path = "src/lib.rs"
